### PR TITLE
pkg/store: use a sync.Once to synchronize channel close

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
> @stevvooe: you can't request testing unless you are a containerd member.

ಠ_ಠ

How I become a member? :angel:

**Comment by Random-Liu** [comment]
/ok-to-test

@stevvooe Your membership need to be public.

**Comment by stevvooe** [comment]
@Random-Liu Set! I think we are good.

"Stephen's conversation with a bot"

**Pull request merged**
